#!/bin/bash

if [ $# -eq 0 ]
then
    echo "Usage: phone searchfor [...searchfor]"
    echo "(You didn't tell me what you want to search for.)"
else
    input=$@
    input="$( echo $input | sed 's/ /|/g')"

    cat data | egrep -i "($input)" | awk 'BEGIN {FS="|"}; {print "--------------->\nname :" $1 "\naddress :" $2 "\nphone :" $3"\n<---------------"}'
fi
